version: '3'

networks: 
  laravel:

services: 
  nginx:
    image: nginx:latest
    container_name: lnginx
    depends_on: 
      - php
      - mysql
    ports: 
      - '80:80'
    volumes: 
      - ./../src:/var/www/html      
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks: 
      - laravel


  mysql:
    image: mysql
    container_name: lmysql
    restart: unless-stopped
    tty: true
    ports: 
      - '4306:3306'
    volumes: 
      - ./db/mysql:/var/lib/mysql
      - ./db/my.cnf:/etc/my.cnf
    environment: 
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel-user
      MYSQL_PASSWORD: laravel-password
      MYSQL_ROOT_PASSWORD: laravel-password
    networks: 
      - laravel

  php:    
    build: 
      context: .
      dockerfile: dockerfile
    container_name: lphp
    volumes: 
      - ./../src:/var/www/html
    ports: 
      - '3000:9000'
    networks: 
      - laravel