version: '3'

networks: 
  cms-laravel:

services: 
  cms-laravel-nginx:
    image: nginx:alpine
    depends_on: 
      - cms-laravel-mysql
      - cms-laravel-php
    ports: 
      - '80:80'
    volumes: 
      - ./../src:/var/www/html      
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks: 
      - cms-laravel

  cms-laravel-mysql:
    image: mysql
    restart: unless-stopped
    tty: true
    ports: 
      - '4306:3306'
    volumes: 
      - ./db/mysql:/var/lib/mysql
      - ./db/my.cnf:/etc/my.cnf
    environment: 
      MYSQL_DATABASE: laravel
      MYSQL_USER: cms-laravel-user
      MYSQL_PASSWORD: cms-laravel-password
      MYSQL_ROOT_PASSWORD: cms-laravel-password
    networks: 
      - cms-laravel

  cms-laravel-php:    
    build: 
      context: .
      dockerfile: ./php/php.yml
    depends_on: 
      - cms-laravel-mysql
    volumes: 
      - ./../src:/var/www/html
    ports: 
      - '3000:9000'
    networks: 
      - cms-laravel